on:
  workflow_run:
    workflows:
      - .NET
    branches:
      - main
    types:
      - completed
  

jobs:
  release:
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
    steps:
        - uses: actions/checkout@v3 
        - name: Setup .NET
          uses: actions/setup-dotnet@v2
          with:
              dotnet-version: 6.0.x
        - name: Restore dependencies
          run: dotnet restore
        - name: Build Release
          run: dotnet build -c Release
        - name: Package Release
          run: dotnet pack -c Release --output target/package
        - name: Build Debug
          run: dotnet build -c Debug
        - name: Package Debug
          run: dotnet pack -c Debug --version-suffix "debug-build" --output target/package
        - name: Push Console User Interface
          run: dotnet nuget push --source "https://api.nuget.org/v3/index.json" --api-key "$env:NUGET_API_KEY" **/ConsoleUserInterface.*.nupkg
        - name: Push Logging Console
          run: dotnet nuget push --source "https://api.nuget.org/v3/index.json" --api-key "$env:NUGET_API_KEY" **/LoggingConsole.*.nupkg
