on:
  workflow_run:
    workflows:
      - .NET
    branches:
      - main
    types:
      - completed
  

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
        - uses: actions/checkout@v3 
        - name: Setup .NET
          uses: actions/setup-dotnet@v2
          with:
              dotnet-version: 6.0.x
        - name: Create Target Directory
          run: mkdir -p ~/work/target/package
        - name: Restore dependencies
          run: dotnet restore
        - name: Package
          run: dotnet pack --no-restore --source "https://api.nuget.org/v3/index.json" --output ~/work/target/package
        - name: Push
          run: dotnet nuget push --api-key "${NUGET_API_KEY}" ~/work/target/package/*.nupkg